### ISSUE TITLE
using default.local configmaps

### ISSUE THREAD

**Issue by fbarreir** [cernops/cvmfs-csi#16]
Following
https://github.com/cernops/cvmfs-csi/blob/master/README.md#configuration

I tried to create a simple default.local configmap like this:
```
CVMFS_REPOSITORIES=atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch
CVMFS_HTTP_PROXY=DIRECT
```
This does not work. 

The cvmfs-csi driver merges the options from my default.local and default.conf into a new config file that is passed to the mount command. But there are a couple of mandatory options  that (at least in the cases I've seen) come from /etc/cvmfs/domain.d/cern.ch.
```
CVMFS_SERVER_URL="http://cvmfs-stratum-one.cern.ch/cvmfs/@fqrn@;http://cernvmfs.gridpp.rl.ac.uk/cvmfs/@fqrn@;http://cvmfs-s1bnl.opensciencegrid.org/cvmfs/@fqrn@;http://cvmfs-s1fnal.opensciencegrid.org/cvmfs/@fqrn@"
CVMFS_KEYS_DIR=/etc/cvmfs/keys/cern.ch
CVMFS_USE_GEOAPI=yes
```

In addition, the cvmfs csi driver requires to run with CVMFS_USER=root.

In the CERN Openstack cluster it works, because your default.local includes these couple of options.

```
[root@cern-extension-kubernetes-1-15-tybqdknmjtvh-node-58 cvmfs]# cat default.local
CVMFS_USER=root
CVMFS_SERVER_URL="http://cvmfs-stratum-one.cern.ch/cvmfs/@fqrn@;http://cernvmfs.gridpp.rl.ac.uk/cvmfs/@fqrn@;http://cvmfs.racf.bnl.gov/cvmfs/@fqrn@;http://cvmfs.fnal.gov/cvmfs/@fqrn@"
CVMFS_KEYS_DIR=/etc/cvmfs/keys/cern.ch
CVMFS_USE_GEOAPI=yes

CVMFS_HTTP_PROXY="http://ca-proxy.cern.ch:3128"
CVMFS_QUOTA_LIMIT=20000
```

**Comment by gman0** [comment]
Hi @, we are overhauling the driver in #39. In the new version of the driver the generated config file is no longer explicitly passed to the mount command -- we're now simply sourcing a ConfigMap into `/etc/cvmfs/config.d` (which admins/users can update during the lifetime of the driver), so I believe the config in domain.d should be picked up by the client now too. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
