### ISSUE TITLE
hardcoded value of CVMFS_HTTP_PROXY only works from within CERN netwok

### ISSUE THREAD

**Issue by lukasheinrich** [cernops/cvmfs-csi#20]
It would be good to have CVMFS_HTTP_PROXY be configurable via values.yml since the current hardcoded value only works from within CERN.

**Comment by gman0** [comment]
Hi @lukasheinrich, we are overhauling the driver in #39. In the new version of the driver, `CVMFS_HTTP_PROXY` can be set in `/etc/cvmfs/config.d` ConfigMap -- no config files are hardcoded now and it should all be user-configurable. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
