### ISSUE TITLE
Attacher requires "patch" permission

### ISSUE THREAD

**Issue by innovate-invent** [cernops/cvmfs-csi#28]
Additional permissions are required that are not demonstrated in the example deployments.

Attacher cluster role:
```
...
  rule {
    api_groups = ["storage.k8s.io"]
    resources  = ["volumeattachments"]
    verbs      = ["get", "list", "watch", "update", "patch"]
  }
  rule {
    api_groups = ["storage.k8s.io"]
    resources  = ["volumeattachments/status"]
    verbs      = ["patch"]
  }
```

**Comment by gman0** [comment]
Hi @innovate-invent, we are overhauling the driver in #39. It no longer uses the external attacher sidecar, so these RBACs are also not necessary. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
